[book]
title = "《文字游戏世界》魔法书"
description = "《文字游戏世界》魔法书"
authors = ["TNOT"]

[output.html]
additional-css = ["src/css/custom.css"]
additional-js = ["src/js/wgw-theme.js"]
default-theme = "wgw-theme"
preferred-dark-theme = "wgw-theme"
